/* ══════════════════════════════════════════
   CHAT
══════════════════════════════════════════ */
let chatReplyToId=null;let chatEditId=null;let activeChatMsgId=null;let voiceRecording=false;let voiceRecordStart=null;let pendingFileData=null;let mediaRecorderObj=null;let audioChunks=[];

function switchGroupTab(tab,btn){
  document.querySelectorAll('.group-detail-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');
  document.querySelectorAll('.group-tab-content').forEach(c=>{c.classList.remove('active');c.style.display='none';});
  const content=document.getElementById('group-'+tab+'-content');
  if(content){content.classList.add('active');content.style.display='block';}
  if(tab==='achievements')renderAchievements();
  if(tab==='workspace'){const badge=document.getElementById('group-chat-notif');if(badge){badge.textContent='0';badge.style.display='none';}}
}
function renderGroupChat(){
  const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;
  const msgs=group.messages||[];const chatEl=document.getElementById('group-chat-messages');
  if(!msgs.length){chatEl.innerHTML='<div class="empty-state" style="padding:20px;font-size:0.78rem">هنوز پیامی نیست</div>';return;}
  chatEl.innerHTML=msgs.slice(-80).map(m=>renderChatMsg(m,group)).join('');chatEl.scrollTop=chatEl.scrollHeight;renderPinnedMessages();
}
function renderChatMsg(m,group){
  const isSelf=m.user===currentUser.username;const t=new Date(m.time);const ts=toPersianNum(String(t.getHours()).padStart(2,'0')+':'+String(t.getMinutes()).padStart(2,'0'));
  let h=`<div class="chat-msg ${isSelf?'self':'other'}" data-msg-id="${m.id}" oncontextmenu="openMsgContextMenu('${m.id}',event)">`;
  h+=`<div class="chat-msg-actions"><button class="msg-action-btn" onclick="openReactionPicker('${m.id}',event)" title="واکنش"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z"/><path d="M7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"/></svg></button><button class="msg-action-btn" onclick="replyToMsg('${m.id}')" title="پاسخ"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 17 4 12 9 7"/><path d="M20 18v-2a4 4 0 0 0-4-4H4"/></svg></button><button class="msg-action-btn" onclick="openMsgContextMenu('${m.id}',event)" title="بیشتر"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg></button></div>`;
  if(m.replyTo&&group){const ref=(group.messages||[]).find(x=>x.id===m.replyTo);if(ref)h+=`<div class="chat-msg-reply-ref"><span class="reply-ref-name">${escapeHtml(ref.displayName||ref.user)}</span><span class="reply-ref-text">${escapeHtml((ref.text||'').substring(0,60))}</span></div>`;}
  h+=`<div class="chat-msg-header"><span class="chat-msg-user">${escapeHtml(m.displayName||m.user)}</span><span class="chat-msg-time">${ts}</span>${m.edited?'<span class="chat-msg-edited">(ویرایش شده)</span>':''}</div>`;
  if(m.type==='file'&&m.fileData){h+=`<div class="chat-msg-file"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg><div class="chat-msg-file-info"><div class="chat-msg-file-name">${escapeHtml(m.fileData.name)}</div><div class="chat-msg-file-size">${escapeHtml(m.fileData.size)}</div></div></div>`;}
  else if(m.type==='image'&&m.fileData){h+=`<img class="chat-msg-image" src="${m.fileData.url}" alt="تصویر" onclick="window.open(this.src,'_blank')">`;}
  else if(m.type==='voice'&&m.voiceData){const dur=m.voiceData.duration||0;const hasAudio=!!m.voiceData.audioUrl;h+=`<div class="chat-msg-voice"><button class="voice-play-btn" onclick="playVoiceMsg('${m.id}',this)" ${!hasAudio?'disabled style="opacity:0.4"':''}><svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg></button><div class="voice-waveform">${generateWaveform(m.voiceData.waveform)}</div><span class="voice-duration">${toPersianNum(dur)}s</span></div>`;}
  if(m.text)h+=`<div class="chat-msg-text">${escapeHtml(m.text)}</div>`;
  if(m.reactions&&m.reactions.length){const grouped={};m.reactions.forEach(r=>{if(!grouped[r.type])grouped[r.type]={users:[],count:0};grouped[r.type].users.push(r.user);grouped[r.type].count++;});h+='<div class="chat-msg-reactions">';Object.entries(grouped).forEach(([type,data])=>{const reacted=data.users.includes(currentUser.username);h+=`<div class="msg-reaction-chip ${reacted?'user-reacted':''}" onclick="toggleReaction('${m.id}','${type}')">${getReactionIcon(type)}<span class="msg-reaction-count">${data.count}</span></div>`;});h+='</div>';}
  if(m.pinned)h+=`<div style="font-size:0.62rem;color:var(--text-muted);margin-top:3px;display:flex;align-items:center;gap:4px"><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>پین شده</div>`;
  h+='</div>';return h;
}
function generateWaveform(data){if(!data||!data.length)return'';const max=Math.max(...data,1);return data.map(h=>`<span style="height:${Math.round(h/max*100)}%"></span>`).join('');}

function sendGroupMessage(){
  const input=document.getElementById('group-chat-input'),text=input.value.trim();if(!currentGroupId)return;
  const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;if(!group.messages)group.messages=[];
  if(chatEditId){const msg=(group.messages||[]).find(m=>m.id===chatEditId);if(msg&&msg.user===currentUser.username){msg.text=text;msg.edited=true;saveGroups(groups);toast('پیام ویرایش شد','info');}chatEditId=null;document.getElementById('chat-edit-preview').style.display='none';input.value='';renderGroupChat();return;}
  if(pendingFileData){const caption=document.getElementById('file-caption-input').value.trim();const msg={id:uid(),user:currentUser.username,displayName:currentUser.displayName||currentUser.username,text:caption,time:Date.now(),type:pendingFileData.type,replyTo:chatReplyToId,reactions:[],pinned:false,fileData:{name:pendingFileData.name,size:pendingFileData.size,url:pendingFileData.url}};group.messages.push(msg);saveGroups(groups);pendingFileData=null;document.getElementById('chat-file-preview').style.display='none';input.value='';chatReplyToId=null;document.getElementById('chat-reply-preview').style.display='none';renderGroupChat();playMessageSound();notifyChatMsg(group,msg);checkAchievements();return;}
  if(!text)return;if(!hasPermission(group,currentUser.username,'send_message')){toast('شما اجازه ارسال پیام ندارید','warn');return;}
  const msg={id:uid(),user:currentUser.username,displayName:currentUser.displayName||currentUser.username,text,time:Date.now(),type:'text',replyTo:chatReplyToId,reactions:[],pinned:false,edited:false};
  group.messages.push(msg);saveGroups(groups);input.value='';chatReplyToId=null;document.getElementById('chat-reply-preview').style.display='none';renderGroupChat();playMessageSound();notifyChatMsg(group,msg);checkAchievements();
}
function handleChatKeydown(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendGroupMessage();}}
function notifyChatMsg(group,msg){if(!settings||settings.notifications.groupChatNotif===false)return;if(msg.user===currentUser.username)return;if(currentGroupId!==group.id){const badge=document.getElementById('group-chat-notif');if(badge){const c=parseInt(badge.textContent)||0;badge.textContent=toPersianNum(c+1);badge.style.display='inline-flex';}}if(settings.notifications.enabled){const dn=msg.displayName||msg.user;const preview=(msg.text||'').substring(0,40)||(msg.type==='voice'?'پیام صوتی':msg.type==='file'?'فایل':'تصویر');toast(`${dn}: ${preview}`,'info');}}
function replyToMsg(msgId){if(!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const msg=(group.messages||[]).find(m=>m.id===msgId);if(!msg)return;chatReplyToId=msgId;document.getElementById('reply-preview-name').textContent=msg.displayName||msg.user;document.getElementById('reply-preview-text').textContent=(msg.text||'').substring(0,60);document.getElementById('chat-reply-preview').style.display='flex';document.getElementById('group-chat-input').focus();document.getElementById('msg-context-menu').style.display='none';document.getElementById('reaction-picker').style.display='none';}
function cancelReply(){chatReplyToId=null;document.getElementById('chat-reply-preview').style.display='none';}
function ctxEditMsg(){if(!activeChatMsgId||!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const msg=(group.messages||[]).find(m=>m.id===activeChatMsgId);if(!msg)return;if(msg.user!==currentUser.username){toast('فقط پیام‌های خودتان قابل ویرایش است','warn');document.getElementById('msg-context-menu').style.display='none';return;}chatEditId=activeChatMsgId;document.getElementById('edit-preview-text').textContent=(msg.text||'').substring(0,60);document.getElementById('chat-edit-preview').style.display='flex';document.getElementById('group-chat-input').value=msg.text||'';document.getElementById('group-chat-input').focus();document.getElementById('msg-context-menu').style.display='none';activeChatMsgId=null;}
function cancelEdit(){chatEditId=null;document.getElementById('chat-edit-preview').style.display='none';document.getElementById('group-chat-input').value='';}
function handleChatFile(event){const file=event.target.files[0];if(!file||!currentGroupId)return;if(!hasPermission(getGroups().find(g=>g.id===currentGroupId),currentUser.username,'send_file')){toast('اجازه ارسال فایل ندارید','warn');return;}const size=file.size>1048576?(file.size/1048576).toFixed(1)+' MB':(file.size/1024).toFixed(0)+' KB';pendingFileData={name:file.name,size,type:'file',url:null};document.getElementById('file-preview-icon').innerHTML='<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>';document.getElementById('file-preview-name').textContent=file.name;document.getElementById('file-preview-size').textContent=size;document.getElementById('file-caption-input').value='';document.getElementById('chat-file-preview').style.display='flex';document.getElementById('file-caption-input').focus();event.target.value='';}
function handleChatImage(event){const file=event.target.files[0];if(!file||!currentGroupId)return;if(!hasPermission(getGroups().find(g=>g.id===currentGroupId),currentUser.username,'send_file')){toast('اجازه ارسال فایل ندارید','warn');return;}const reader=new FileReader();reader.onload=function(e){pendingFileData={name:file.name,size:'',type:'image',url:e.target.result};document.getElementById('file-preview-icon').innerHTML='<img src="'+e.target.result+'" style="width:36px;height:36px;border-radius:8px;object-fit:cover">';document.getElementById('file-preview-name').textContent=file.name;document.getElementById('file-preview-size').textContent='تصویر';document.getElementById('file-caption-input').value='';document.getElementById('chat-file-preview').style.display='flex';document.getElementById('file-caption-input').focus();event.target.value='';};reader.readAsDataURL(file);}
function cancelFileUpload(){pendingFileData=null;document.getElementById('chat-file-preview').style.display='none';}
function openReactionPicker(msgId,event){event.stopPropagation();activeChatMsgId=msgId;const picker=document.getElementById('reaction-picker');const rect=event.currentTarget.getBoundingClientRect();picker.style.display='flex';picker.style.position='fixed';picker.style.top=Math.max(4,rect.top-46)+'px';picker.style.left=Math.min(rect.left,window.innerWidth-200)+'px';}
function addReaction(type){if(!activeChatMsgId||!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const msg=(group.messages||[]).find(m=>m.id===activeChatMsgId);if(!msg)return;if(!msg.reactions)msg.reactions=[];const existing=msg.reactions.find(r=>r.user===currentUser.username&&r.type===type);if(existing)msg.reactions=msg.reactions.filter(r=>!(r.user===currentUser.username&&r.type===type));else{msg.reactions=msg.reactions.filter(r=>r.user!==currentUser.username);msg.reactions.push({user:currentUser.username,type});}saveGroups(groups);document.getElementById('reaction-picker').style.display='none';activeChatMsgId=null;renderGroupChat();}
function toggleReaction(msgId,type){activeChatMsgId=msgId;addReaction(type);}
function openMsgContextMenu(msgId,event){event.preventDefault();event.stopPropagation();activeChatMsgId=msgId;const menu=document.getElementById('msg-context-menu');menu.style.display='flex';menu.style.position='fixed';menu.style.top=Math.min(event.clientY,window.innerHeight-200)+'px';menu.style.left=Math.min(event.clientX,window.innerWidth-200)+'px';}
function ctxReplyToMsg(){if(activeChatMsgId)replyToMsg(activeChatMsgId);document.getElementById('msg-context-menu').style.display='none';}
function ctxPinMsg(){if(!activeChatMsgId||!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;if(!hasPermission(group,currentUser.username,'pin_message')){toast('اجازه پین کردن ندارید','warn');document.getElementById('msg-context-menu').style.display='none';return;}const msg=(group.messages||[]).find(m=>m.id===activeChatMsgId);if(msg){msg.pinned=!msg.pinned;saveGroups(groups);renderGroupChat();toast(msg.pinned?'پیام پین شد':'پیام از پین خارج شد','info');}document.getElementById('msg-context-menu').style.display='none';activeChatMsgId=null;}
function ctxCopyMsg(){if(!activeChatMsgId||!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const msg=(group.messages||[]).find(m=>m.id===activeChatMsgId);if(msg&&msg.text&&navigator.clipboard)navigator.clipboard.writeText(msg.text);toast('متن کپی شد','success');document.getElementById('msg-context-menu').style.display='none';activeChatMsgId=null;}
function ctxDeleteMsg(){if(!activeChatMsgId||!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const msg=(group.messages||[]).find(m=>m.id===activeChatMsgId);const isOwn=msg&&msg.user===currentUser.username;if(!isOwn&&!hasPermission(group,currentUser.username,'delete_others')){toast('اجازه حذف پیام دیگران را ندارید','warn');document.getElementById('msg-context-menu').style.display='none';return;}if(!confirm('این پیام حذف شود؟')){document.getElementById('msg-context-menu').style.display='none';activeChatMsgId=null;return;}group.messages=(group.messages||[]).filter(m=>m.id!==activeChatMsgId);saveGroups(groups);renderGroupChat();toast('پیام حذف شد','warn');document.getElementById('msg-context-menu').style.display='none';activeChatMsgId=null;}
function toggleChatSearch(){const bar=document.getElementById('chat-search-bar');bar.style.display=bar.style.display==='none'?'flex':'none';if(bar.style.display!=='none')document.getElementById('chat-search-input').focus();else{document.getElementById('chat-search-input').value='';renderGroupChat();}}
function searchChatMessages(query){if(!query||!currentGroupId){renderGroupChat();return;}const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const filtered=(group.messages||[]).filter(m=>(m.text||'').toLowerCase().includes(query.toLowerCase())||(m.displayName||'').toLowerCase().includes(query.toLowerCase()));const chatEl=document.getElementById('group-chat-messages');if(!filtered.length){chatEl.innerHTML='<div class="empty-state" style="padding:20px;font-size:0.78rem">پیامی یافت نشد</div>';return;}chatEl.innerHTML=filtered.slice(-50).map(m=>renderChatMsg(m,group)).join('');}
function togglePinnedMessages(){const area=document.getElementById('chat-pinned-area');area.style.display=area.style.display==='none'?'block':'none';if(area.style.display!=='none')renderPinnedMessages();}
function renderPinnedMessages(){if(!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;const pinned=(group.messages||[]).filter(m=>m.pinned);const list=document.getElementById('pinned-messages-list');if(!pinned.length){list.innerHTML='<div style="padding:12px;text-align:center;font-size:0.78rem;color:var(--text-muted)">پیام پین شده‌ای نیست</div>';return;}list.innerHTML=pinned.map(m=>`<div class="pinned-msg-item" onclick="scrollToMsg('${m.id}')"><span class="pinned-msg-user">${escapeHtml(m.displayName||m.user)}</span><span class="pinned-msg-text">${escapeHtml((m.text||'').substring(0,50))}</span></div>`).join('');}
function scrollToMsg(msgId){const el=document.querySelector(`[data-msg-id="${msgId}"]`);if(el)el.scrollIntoView({behavior:'smooth',block:'center'});}
function scrollChatToBottom(){const c=document.getElementById('group-chat-messages');if(c)c.scrollTop=c.scrollHeight;}
function toggleAttachmentMenu(){const m=document.getElementById('attachment-menu');m.classList.toggle('attachment-menu-mobile',isMobileDevice());m.style.display=m.style.display==='none'?'block':'none';}
function triggerChatFileUpload(){document.getElementById('chat-file-input').click();document.getElementById('attachment-menu').style.display='none';}
function triggerChatImageUpload(){document.getElementById('chat-image-input').click();document.getElementById('attachment-menu').style.display='none';}

/* ── VOICE RECORDING (REAL) ── */
function startVoiceRecord(){
  if(!currentGroupId)return;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){toast('مرورگر شما از ضبط صدا پشتیبانی نمی‌کند','warn');return;}
  const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group||!hasPermission(group,currentUser.username,'send_voice')){toast('اجازه ارسال پیام صوتی ندارید','warn');return;}
  navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{
    mediaRecorderObj=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm'});
    audioChunks=[];mediaRecorderObj.ondataavailable=e=>{if(e.data.size>0)audioChunks.push(e.data);};
    mediaRecorderObj.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(audioChunks,{type:mediaRecorderObj.mimeType||'audio/webm'});if(blob.size<100){voiceRecording=false;document.getElementById('voice-record-btn').classList.remove('recording');return;}const reader=new FileReader();reader.onload=function(){sendVoiceMessage(reader.result,Math.max(1,Math.round((Date.now()-voiceRecordStart)/1000)));};reader.readAsDataURL(blob);};
    mediaRecorderObj.start(100);voiceRecording=true;voiceRecordStart=Date.now();document.getElementById('voice-record-btn').classList.add('recording');startVoiceTimer();
  }).catch(()=>{toast('دسترسی به میکروفون داده نشد','warn');});
}
let voiceTimerInterval=null;
function startVoiceTimer(){const durEl=document.getElementById('voice-record-duration');if(voiceTimerInterval)clearInterval(voiceTimerInterval);voiceTimerInterval=setInterval(()=>{if(!voiceRecording){clearInterval(voiceTimerInterval);voiceTimerInterval=null;return;}const elapsed=Math.floor((Date.now()-voiceRecordStart)/1000);if(durEl)durEl.textContent=toPersianNum(String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(elapsed%60).padStart(2,'0'));},200);}
function stopVoiceRecord(){if(!voiceRecording||!mediaRecorderObj)return;voiceRecording=false;document.getElementById('voice-record-btn').classList.remove('recording');if(mediaRecorderObj.state!=='inactive')mediaRecorderObj.stop();}
function sendVoiceMessage(audioDataUrl,duration){if(!currentGroupId||duration<1)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;if(!group.messages)group.messages=[];const waveform=Array.from({length:24},()=>Math.random()*70+30);const msg={id:uid(),user:currentUser.username,displayName:currentUser.displayName||currentUser.username,text:'',time:Date.now(),type:'voice',replyTo:chatReplyToId,reactions:[],pinned:false,voiceData:{duration,waveform,audioUrl:audioDataUrl}};group.messages.push(msg);saveGroups(groups);chatReplyToId=null;document.getElementById('chat-reply-preview').style.display='none';renderGroupChat();playMessageSound();notifyChatMsg(group,msg);checkAchievements();}

/* ── VOICE PLAYBACK (REAL) ── */
function playVoiceMsg(msgId,btn){
  if(!currentGroupId)return;const groups=getGroups(),group=groups.find(g=>g.id===currentGroupId);if(!group)return;
  const msg=(group.messages||[]).find(m=>m.id===msgId);if(!msg||!msg.voiceData)return;
  if(btn.classList.contains('playing')){btn.classList.remove('playing');btn.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>';if(window._voiceAudio){window._voiceAudio.pause();window._voiceAudio.currentTime=0;window._voiceAudio=null;}return;}
  document.querySelectorAll('.voice-play-btn.playing').forEach(b=>{b.classList.remove('playing');b.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>';});
  if(window._voiceAudio){window._voiceAudio.pause();window._voiceAudio.currentTime=0;}
  if(!msg.voiceData.audioUrl){toast('فایل صوتی موجود نیست','warn');return;}
  const audio=new Audio(msg.voiceData.audioUrl);window._voiceAudio=audio;btn.classList.add('playing');btn.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>';
  const voiceContainer=btn.closest('.chat-msg-voice');const waveform=voiceContainer?voiceContainer.querySelector('.voice-waveform'):null;const bars=waveform?waveform.querySelectorAll('span'):[];
  audio.play().catch(()=>{btn.classList.remove('playing');btn.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>';});
  audio.ontimeupdate=()=>{if(!bars.length||!audio.duration)return;const progress=audio.currentTime/audio.duration;const activeIdx=Math.floor(progress*bars.length);bars.forEach((b,j)=>b.classList.toggle('active',j<=activeIdx));};
  audio.onended=()=>{btn.classList.remove('playing');btn.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>';bars.forEach(b=>b.classList.remove('active'));window._voiceAudio=null;};
}
function copyGroupCode(){const el=document.getElementById('group-detail-code');const code=el.textContent;if(navigator.clipboard)navigator.clipboard.writeText(code);toast('کد گروه کپی شد: '+code,'success');}

document.addEventListener('click',e=>{if(!e.target.closest('.reaction-picker')&&!e.target.closest('.msg-action-btn')){const rp=document.getElementById('reaction-picker');if(rp)rp.style.display='none';}if(!e.target.closest('.msg-context-menu')&&!e.target.closest('.chat-msg')){const cm=document.getElementById('msg-context-menu');if(cm)cm.style.display='none';}if(!e.target.closest('.chat-tool-wrapper')){const am=document.getElementById('attachment-menu');if(am)am.style.display='none';}});
/* ══════════════════════════════════════════
   CANCEL VOICE RECORD (preview)
══════════════════════════════════════════ */
function cancelVoiceRecord() {
  if (voiceRecording) {
    voiceRecording = false;
    if (mediaRecorderObj && mediaRecorderObj.state !== 'inactive') {
      mediaRecorderObj.stop();
    }
  }
  document.getElementById('voice-record-btn').classList.remove('recording');
  document.getElementById('chat-voice-preview').style.display = 'none';
}
